#!/usr/bin/env python3
"""Generate etc/protocol-vectors.json from one list of canonical frames.

The host is not written yet and may not be C#, so the contract ships as
data rather than as a reference implementation: any language that can
parse JSON can assert its encoder and decoder against these.

Run after changing PROTOCOL.md; it also prints the Markdown table so the
spec and the JSON cannot drift.

    python etc/gen-vectors.py
"""

import json
import os

PROTOCOL_VERSION = 1
SOF = 0xAB

TYPE_NAMES = {
    0x00: "PANIC",
    0x01: "KEY_DOWN",
    0x02: "KEY_UP",
    0x03: "MOUSE_MOVE",
    0x04: "MOUSE_BTN",
    0x05: "MOUSE_WHEEL",
    0x06: "SCREEN_SIZE",
    0x07: "PING",
    0x80: "PONG",
    0x81: "NACK",
}


def u16(v):
    return bytes([v & 0xFF, (v >> 8) & 0xFF])


def frame(type_, payload=b""):
    checksum = (type_ + len(payload) + sum(payload)) & 0xFF
    return bytes([SOF, type_, len(payload)]) + payload + bytes([checksum])


# name, type, payload, decoded fields
CASES = [
    ("panic",                 0x00, b"",                        {}),
    ("key_down_a",            0x01, bytes([0x04]),              {"usage": 0x04}),
    ("key_up_a",              0x02, bytes([0x04]),              {"usage": 0x04}),
    ("key_down_left_shift",   0x01, bytes([0xE1]),              {"usage": 0xE1}),
    ("key_up_left_shift",     0x02, bytes([0xE1]),              {"usage": 0xE1}),
    ("mouse_move_960_540",    0x03, u16(960) + u16(540),        {"x": 960, "y": 540}),
    ("mouse_move_origin",     0x03, u16(0) + u16(0),            {"x": 0, "y": 0}),
    ("mouse_btn_left_down",   0x04, bytes([0x01]),              {"mask": 0x01}),
    ("mouse_btn_released",    0x04, bytes([0x00]),              {"mask": 0x00}),
    ("mouse_wheel_up_1",      0x05, bytes([0x01, 0x00]),        {"vert": 1, "horiz": 0}),
    ("mouse_wheel_down_1",    0x05, bytes([0xFF, 0x00]),        {"vert": -1, "horiz": 0}),
    ("screen_size_1920_1080", 0x06, u16(1920) + u16(1080),      {"width": 1920, "height": 1080}),
    ("ping",                  0x07, b"",                        {}),
    ("pong_v1",               0x80, bytes([PROTOCOL_VERSION]),  {"version": PROTOCOL_VERSION}),
    ("nack_checksum",         0x81, bytes([0x01]),              {"reason": 1}),
]


def main():
    vectors = []
    for name, type_, payload, fields in CASES:
        raw = frame(type_, payload)
        vectors.append({
            "name": name,
            "direction": "device_to_host" if type_ >= 0x80 else "host_to_device",
            "type": type_,
            "typeName": TYPE_NAMES[type_],
            "fields": fields,
            "hex": " ".join("%02X" % b for b in raw),
            "bytes": list(raw),
        })

    doc = {
        "protocolVersion": PROTOCOL_VERSION,
        "sof": SOF,
        "checksum": "(type + len + payload bytes) & 0xFF",
        "byteOrder": "little-endian",
        "note": "Generated by etc/gen-vectors.py. Do not hand-edit.",
        "vectors": vectors,
    }

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "protocol-vectors.json")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        json.dump(doc, f, indent=2)
        f.write("\n")

    print("wrote %s (%d vectors)\n" % (out, len(vectors)))
    print("| Message | Bytes |")
    print("|---------|-------|")
    for v in vectors:
        print("| %s | `%s` |" % (v["name"], v["hex"]))


if __name__ == "__main__":
    main()
